name: CI

on: [push, pull_request]

jobs:

  build:    
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno_version: ['v0.35.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      DENO_INSTALL:  

    steps:

    - name: Configure git
      run: git config --global core.symlinks true

    - name: Clone repository
      uses: actions/checkout@v1

    - name: Environment (common)
      run: |
        echo "::set-env name=DENO_INSTALL::$HOME/.local"
        echo "::add-path::$HOME/.local/bin"

    - name: Environment (echo)
      run: |
        echo DENO_INSTALL: $DENO_INSTALL
        echo PATH: $PATH

    - name: Setup deno ${{ matrix.deno_version }} on ${{ matrix.os }}
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s ${{ matrix.deno_version }}
        deno -h

    - name: Run deno test's
      run: deno test --allow-env
