name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:    
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      deno: /home/runner/.local/bin/deno
    strategy:
      matrix:
        deno_version: ['v0.35.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup deno ${{ matrix.deno_version }} on ${{ matrix.os }}
      run: curl -fsSL https://deno.land/x/install/install.sh | sh -s ${{ matrix.deno_version }} && $deno -h

    - name: Run deno test's
      run: $deno test --allow-env
