name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:    
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      deno: ~/.local/bin/deno
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup deno v0.35.0 on ${{ matrix.os }}
      run: curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.35.0 && $deno -h

    - name: Run deno test's
      run: $deno test --allow-env
